version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    command: 'postgres -c max_connections=100 -c shared_buffers=96MB -c checkpoint_timeout=600 -c synchronous_commit=off -c fsync=off -c full_page_writes=off -c work_mem=16MB'
    restart: always
    environment:
      POSTGRES_DB: rinhadb
      POSTGRES_USER: rinha
      POSTGRES_PASSWORD: rinha123
    ports:
      - "5432:5432"
    volumes:
      - ./../config/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
